import burgerImage from '../assets/images/burgerImage.png'
import pizzaImage from '../assets/images/pizzaImage.jpg'
import asianImage from '../assets/images/asianImage.jpg'
import dessertImage from '../assets/images/dessertImage.jpg'
import drinkImage from '../assets/images/drinkImage.png'

const FoodData = [
  // Burgers
  {
    id: 1,
    name: "Classic Beef Burger",
    category: "Burgers",
    price: 6.99,
    rating: 4.7,
    reviews: 245,
    discount: 10,
    image: burgerImage,
  },
  {
    id: 2,
    name: "Double Cheese Burger",
    category: "Burgers",
    price: 8.49,
    rating: 4.9,
    reviews: 412,
    discount: 15,
    image: burgerImage,
  },
  {
    id: 3,
    name: "Crispy Chicken Burger",
    category: "Burgers",
    price: 7.49,
    rating: 4.6,
    reviews: 198,
    discount: 20,
    image: burgerImage,
  },
  {
    id: 4,
    name: "Spicy Jalapeño Burger",
    category: "Burgers",
    price: 7.99,
    rating: 4.8,
    reviews: 276,
    discount: 10,
    image: burgerImage,
  },

  // Pizza
  {
    id: 5,
    name: "Veggie Supreme Pizza",
    category: "Pizza",
    price: 7.49,
    rating: 4.8,
    reviews: 320,
    discount: 20,
    image: pizzaImage,
  },
  {
    id: 6,
    name: "Pepperoni Feast Pizza",
    category: "Pizza",
    price: 9.99,
    rating: 4.9,
    reviews: 487,
    discount: 15,
    image: pizzaImage,
  },
  {
    id: 7,
    name: "BBQ Chicken Pizza",
    category: "Pizza",
    price: 10.49,
    rating: 4.7,
    reviews: 264,
    discount: 10,
    image: pizzaImage,
  },
  {
    id: 8,
    name: "Four Cheese Pizza",
    category: "Pizza",
    price: 8.99,
    rating: 4.6,
    reviews: 189,
    discount: 25,
    image: pizzaImage,
  },

  // Asian
  {
    id: 9,
    name: "Chicken Teriyaki",
    category: "Asian",
    price: 8.99,
    rating: 4.8,
    reviews: 231,
    discount: 10,
    image: asianImage,
  },
  {
    id: 10,
    name: "Beef Chow Mein",
    category: "Asian",
    price: 7.99,
    rating: 4.7,
    reviews: 175,
    discount: 15,
    image: asianImage,
  },
  {
    id: 11,
    name: "Chicken Fried Rice",
    category: "Asian",
    price: 6.99,
    rating: 4.6,
    reviews: 298,
    discount: 20,
    image: asianImage,
  },
  {
    id: 12,
    name: "Spicy Ramen Bowl",
    category: "Asian",
    price: 9.49,
    rating: 4.9,
    reviews: 342,
    discount: 10,
    image: asianImage,
  },

  // Desserts
  {
    id: 13,
    name: "Chocolate Lava Cake",
    category: "Desserts",
    price: 5.49,
    rating: 4.9,
    reviews: 356,
    discount: 15,
    image: dessertImage,
  },
  {
    id: 14,
    name: "Classic Cheesecake",
    category: "Desserts",
    price: 4.99,
    rating: 4.8,
    reviews: 287,
    discount: 10,
    image: dessertImage,
  },
  {
    id: 15,
    name: "Strawberry Ice Cream",
    category: "Desserts",
    price: 3.99,
    rating: 4.7,
    reviews: 214,
    discount: 20,
    image: dessertImage,
  },
  {
    id: 16,
    name: "Chocolate Brownie",
    category: "Desserts",
    price: 4.49,
    rating: 4.8,
    reviews: 241,
    discount: 15,
    image: dessertImage,
  },

  // Drinks
  {
    id: 17,
    name: "Classic Cola",
    category: "Drinks",
    price: 1.99,
    rating: 4.5,
    reviews: 156,
    discount: 5,
    image: drinkImage,
  },
  {
    id: 18,
    name: "Fresh Lemonade",
    category: "Drinks",
    price: 2.99,
    rating: 4.8,
    reviews: 203,
    discount: 10,
    image: drinkImage,
  },
  {
    id: 19,
    name: "Mango Smoothie",
    category: "Drinks",
    price: 4.49,
    rating: 4.9,
    reviews: 318,
    discount: 15,
    image: drinkImage,
  },
  {
    id: 20,
    name: "Iced Coffee",
    category: "Drinks",
    price: 3.49,
    rating: 4.7,
    reviews: 267,
    discount: 10,
    image: drinkImage,
  },
  {
    id: 21,
    category: "All"
  }
];

export default FoodData;       